import type { CoverVariation } from "@/types/covers";

export const PRESET_VARIATIONS: CoverVariation[] = [
  {
    name: 'Midnight Pro',
    description: 'Dark and authoritative',
    layout: 'centered',
    background: { type: 'gradient', gradient: { angle: 135, stops: [{ color: '#1a1a2e', position: 0 }, { color: '#0f3460', position: 100 }] } },
    textColors: { title: '#ffffff', subtitle: 'rgba(255,255,255,0.75)', author: 'rgba(255,255,255,0.5)' },
    accentColor: '#e94560',
    fonts: { title: 'Playfair Display', subtitle: 'Lato', author: 'Montserrat' },
  },
  {
    name: 'Forest Sage',
    description: 'Natural and calming',
    layout: 'bold',
    background: { type: 'gradient', gradient: { angle: 160, stops: [{ color: '#1b4332', position: 0 }, { color: '#2d6a4f', position: 100 }] } },
    textColors: { title: '#d8f3dc', subtitle: '#95d5b2', author: '#74c69d' },
    accentColor: '#52b788',
    fonts: { title: 'Merriweather', subtitle: 'Lato', author: 'Montserrat' },
  },
  {
    name: 'Violet Dream',
    description: 'Creative and modern',
    layout: 'creative',
    background: { type: 'gradient', gradient: { angle: 145, stops: [{ color: '#240046', position: 0 }, { color: '#5a189a', position: 60 }, { color: '#9d4edd', position: 100 }] } },
    textColors: { title: '#ffffff', subtitle: '#e0aaff', author: 'rgba(255,255,255,0.5)' },
    accentColor: '#c77dff',
    fonts: { title: 'Poppins', subtitle: 'Poppins', author: 'Poppins' },
  },
  {
    name: 'Slate Clean',
    description: 'Minimal and corporate',
    layout: 'minimal',
    background: { type: 'solid', color: '#f8fafc' },
    textColors: { title: '#0f172a', subtitle: '#334155', author: '#94a3b8' },
    accentColor: '#6366f1',
    fonts: { title: 'Playfair Display', subtitle: 'Lato', author: 'Montserrat' },
  },
  {
    name: 'Crimson Power',
    description: 'Bold and energetic',
    layout: 'professional',
    background: { type: 'gradient', gradient: { angle: 135, stops: [{ color: '#1c0a00', position: 0 }, { color: '#8b0000', position: 100 }] } },
    textColors: { title: '#ffffff', subtitle: 'rgba(255,200,200,0.85)', author: 'rgba(255,255,255,0.5)' },
    accentColor: '#ff6b6b',
    fonts: { title: 'Montserrat', subtitle: 'Lato', author: 'Montserrat' },
  },
  {
    name: 'Golden Hour',
    description: 'Warm and inviting',
    layout: 'split',
    background: { type: 'gradient', gradient: { angle: 160, stops: [{ color: '#92400e', position: 0 }, { color: '#d97706', position: 100 }] } },
    textColors: { title: '#ffffff', subtitle: 'rgba(255,255,255,0.9)', author: '#fef3c7' },
    accentColor: '#fbbf24',
    fonts: { title: 'Playfair Display', subtitle: 'Lato', author: 'Raleway' },
  },
  {
    name: 'Indigo Elite',
    description: 'Premium and tech-forward',
    layout: 'bold',
    background: { type: 'gradient', gradient: { angle: 135, stops: [{ color: '#1e1b4b', position: 0 }, { color: '#3730a3', position: 100 }] } },
    textColors: { title: '#e0e7ff', subtitle: 'rgba(199,210,254,0.85)', author: 'rgba(165,180,252,0.6)' },
    accentColor: '#818cf8',
    fonts: { title: 'Poppins', subtitle: 'Poppins', author: 'Raleway' },
  },
  {
    name: 'Arctic White',
    description: 'Clean and professional',
    layout: 'professional',
    background: { type: 'gradient', gradient: { angle: 180, stops: [{ color: '#f0f9ff', position: 0 }, { color: '#e0f2fe', position: 100 }] } },
    textColors: { title: '#0c4a6e', subtitle: '#0369a1', author: '#7dd3fc' },
    accentColor: '#0ea5e9',
    fonts: { title: 'Raleway', subtitle: 'Lato', author: 'Montserrat' },
  },
];
